name = "arbitrage-bot"
type = "javascript"
webpack_config = "webpack.config.js"
route = ''
zone_id = ''
usage_model = ''
compatibility_flags = []
workers_dev = true
compatibility_date = "2021-10-30"

[triggers]
crons = ["* * * * *"]

[build]
command = "npm install && npm run worker:build"

[build.upload]
format = "service-worker"
